// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ReduxProvider } from "@/redux/ReduxProvider";
// import { Toaster } from "react-hot-toast";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased `}
//       >
//       <ReduxProvider>
//         <Toaster position="top-right" reverseOrder={false}/>
//        {children}
//       </ReduxProvider>
      
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next"
import { Figtree } from "next/font/google"
import "./globals.css"
import { ReduxProvider } from "@/redux/ReduxProvider"
import { Toaster } from "react-hot-toast"
import Header from "@/components/Header"
import { AuthProvider } from "@/context/AuthContext"

const figtree = Figtree({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Talmira",
  description: "Job tracking app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`pt-[60px] ${figtree.className} antialiased bg-gradient-to-br from-[#366157] to-[#e6fffa] min-h-screen`}>
        <ReduxProvider>
          <AuthProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Header/>
          {children}
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
